### ISSUE TITLE
fakeClick method no longer works in Chrome 41

### ISSUE THREAD

**Issue by tomsouthall-zz** [lhache/deviant.popunder#1]
The fakeClick tab-under method works fine in versions of Chrome < 41. 

In Chrome 41 (currently only available in Chrome Canary) focus switches to the new tab.

**Comment by gibigate** [comment]
+1

**Comment by lwih** [comment]
Guys, I'll take care of it, there will be an update within a month.

**Comment by lwih** [comment]
Old => closing
